stages:
  - test

test-job:
  stage: test
  script: 
    - docker compose -f RandomEmailGenerator/docker-compose.yml down
    - docker compose -f RandomEmailGenerator/docker-compose.yml build random_email_generator
    - docker compose -f RandomEmailGenerator/docker-compose.yml up