image : mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - test

test:
  stage: test
  script:
    - echo Test
    - dotnet test ~/RandomEmailGenerator/RandomEmailGenerator.csproj
    - dotnet run --project ./RandomEmailGenerator/RandomEmailGenerator.csproj alex def def.com 4
  artifacts:
    paths:
      - test/